app/projects/[id]/meeting-notes/page.tsx, components/project/meeting-notes/MeetingNoteCard.tsx, components/project/meeting-notes/MeetingNotes.tsx, components/project/meeting-notes/MeetingNotesAdd.tsx, package-lock.json
- 관련 지라 티켓: [CM-22](https://starmix.atlassian.net/browse/CM-22)
- 회의록 페이지(meeting-notes) 생성: 필터, 검색창, 회의록 추가, 예시 회의록
=> [CM-22] 회의록 페이지 생성

app/projects/[id]/layout.tsx, app/projects/[id]/meeting-notes/tip/Editor.tsx, app/projects/[id]/meeting-notes/tip/Room.tsx, app/projects/[id]/meeting-notes/tip/Threads.tsx, app/projects/[id]/meeting-notes/tip/page.tsx, components/project/epic/sampleTasks.ts, eslint.config.mjs, liveblocks.config.ts, package-lock.json, package.json
- 관련 지라 티켓: [CM-36](https://starmix.atlassian.net/browse/CM-36)
- Liveblocks 패키지를 설치
- 회의록 기능에서 공동 편집 기능 추가
=> [CM-36] 회의록 Liveblocks PoC

components/project/Sidebar.tsx, components/project/home/ProjectAdd.tsx, next.config.ts
- 관련 지라 티켓: [CM-35](https://starmix.atlassian.net/browse/CM-35)
- Next.js의 boilerplate 페이지가 보이는 root 경로를 projects 경로로 리디렉션
- 프로젝트 생성 버튼 클릭 핸들링 및 사이드바 acitve 효과 적용
=> [CM-35] 프로젝트 라우트 개선

app/invite/[token]/page.tsx, components/ui/badge.tsx, package-lock.json, package.json
- 관련 지라 티켓: [CM-40](https://starmix.atlassian.net/browse/CM-40)
- 팀원 초대에 대해 수락 또는 거절할 수 있는 페이지를 생성
- shadcn ui의 badge 컴포넌트 의존성 추가
=> [CM-40] 팀원 초대 및 승인 페이지 생성

components/project/new/ChatPhase.tsx, components/project/new/phases.ts, components/ui/button.tsx, components/ui/calendar.tsx, components/ui/file-upload.tsx, components/ui/popover.tsx, components/ui/text-field.tsx, package-lock.json, package.json, types/phase.ts
- 관련 지라 티켓: [CM-41](https://starmix.atlassian.net/browse/CM-41)
- 프로젝트 생성 시에 프롬프트 입력에 대한 형식을 제한하는 기능을 추가
- Table 또는 Form 형태로 입력하는 형식은 추후 구현 예정
=> [CM-41] 새 프로젝트 생성 시 입력 형식 제한

.github/workflows/vercel.yml, package.json
- 관련 지라 티켓: [CM-58](https://starmix.atlassian.net/browse/CM-58)
- 빌드 오류 검증을 위한 워크플로우를 추가
=> [CM-58] GitHub Action에 빌드 오류 검증 과정 추가

app/utils/authOptions.ts, components/SyncAuthState.tsx, stores/useAuthStore.ts, tsconfig.json, types/next-auth.d.ts
- 관련 지라 티켓: [CM-62](https://starmix.atlassian.net/browse/CM-62)
- 로그인 시에 백엔드로부터 응답받은 JWT을 저장하도록 코드를 수정
=> [CM-62] Google 로그인 callback으로 응답받은 JWT token을 저장

app/projects/page.tsx, components/project/home/ProjectCard.tsx, components/project/home/ProjectFilter.tsx, components/project/home/ProjectList.tsx, types/project.ts
- 관련 지라 티켓: [CM-60](https://starmix.atlassian.net/browse/CM-60)
- 전체 프로젝트 목록을 Server로부터 fetch하는 로직을 추가
- Response Body 필드에 맞추어 Project Type을 정의
- 새로 정의된 Project Type에 따라 Project Card에 전달하는 props 수정
=> [CM-60] 전체 프로젝트 목록 API 요청

app/globals.css, app/projects/page.tsx, components/LoadingCheckMate.tsx
- 관련 지라 티켓: [CM-67](https://starmix.atlassian.net/browse/CM-67)
- 로딩 컴포넌트를 추가하고 로딩 화면으로 적용
https://github.com/user-attachments/assets/4c9be7f0-f8c0-463b-bd87-6c9a291b6ac8
=> [CM-67] 로딩 컴포넌트 추가

.github/workflows/vercel.yml
- 관련 지라 티켓: [CM-78](https://starmix.atlassian.net/browse/CM-78)
- Starmix Vercel 계정으로 배포되도록 GitHub Actions를 수정
=> [CM-78] GitHub Actions 레포지토리와 토큰 수정

.github/workflows/vercel.yml, app/layout.tsx, app/projects/layout.tsx, app/projects/new/page.tsx, components/Navbar.tsx, components/project/new/ChatPhase.tsx, components/project/new/DataTable.tsx, components/project/new/FeatureTable.tsx, components/project/new/FormPhase.tsx, components/project/new/GenericEditableTable.tsx, components/project/new/ProjectWizard.tsx, components/project/new/TeamMemberTable.tsx, components/project/new/columns.tsx, components/project/new/phases.ts, types/NewProjectTeamMember.ts, types/project-creation.ts
- 관련 지라 티켓: [CM-79](https://starmix.atlassian.net/browse/CM-79)
- 프로젝트 생성 시 팀원 정보가 제대로 전송되도록 수정
- 프로젝트 생성의 기능 정의 Table 편집이 가능하도록 기능 추가
=> [CM-79] 프로젝트 생성 시 응답으로 생성된 기능 정의 Table 렌더링

app/globals.css, app/projects/[id]/newsprint/page.tsx, components/CheckMateSpinner.tsx, components/LoadingCheckMate.tsx, components/project/sprint/DetailTaskTable.tsx, components/project/sprint/EditableTable.tsx, components/project/sprint/LoadingScreen.tsx, components/project/sprint/ReadOnlyTable.tsx, components/project/sprint/SprintReviewTable.tsx, components/project/sprint/SprintWizard.tsx, components/ui/button.tsx, tailwind.config.js
- 관련 지라 티켓: [CM-81](https://starmix.atlassian.net/browse/CM-81)
- 프로젝트 스프린트 재구성 페이지를 생성
- 프로젝트 스프린트 재구성 과정 네 단계의 UI를 구현
- 프로젝트 스프린트 재구성 과정의 로딩 화면을 추가
=> [CM-81] 프로젝트 스프린트 재구성 페이지 생성

app/globals.css, components/project/overview/DailyScrumCard.tsx
- 관련 지라 티켓: [CM-56](https://starmix.atlassian.net/browse/CM-56)
- 프로젝트 오버뷰의 데일리 스크럼 위젯에서 사용자별 태스크를 확인할 수 있는 기능을 추가
- 프로젝트 오버뷰의 데일리 스크럼 위젯 디자인 적용
=> [CM-56] 프로젝트 오버뷰 데일리스크럼 위젯 디자인 적용

app/projects/[id]/overview/page.tsx, components/project/overview/ProjectHeader.tsx, types/project.ts
- 관련 지라 티켓: [CM-94](https://starmix.atlassian.net/browse/CM-94)
- 프로젝트 오버뷰에서 프로젝트 기본 정보를 서버로부터 조회
=> [CM-94] 프로젝트 오버뷰 API 적용

app/globals.css, components/project/Sidebar.tsx, components/ui/sidebar.tsx, stores/useProjectStore.ts
- 관련 지라 티켓: [CM-90](https://starmix.atlassian.net/browse/CM-90)
- 사이드바 디자인 적용
- 사이드바 item을 a 대신 Link로 개선
=> [CM-90] 사이드바 디자인 적용

app/projects/page.tsx, components/project/home/ProjectCard.tsx, components/project/home/ProjectFilter.tsx, components/project/home/ProjectList.tsx, types/project.ts
- 관련 지라 티켓: [CM-101](https://starmix.atlassian.net/browse/CM-101)
- 프로젝트 전체 리스트 조회 시의 타입 문제를 해결
- 프로젝트 전체 리스트 조회 시에 필터링이 작동되지 않던 문제를 해결
=> [CM-101] API의 project schema 변경 대응

app/layout.tsx, components/Navbar.tsx, components/ToastProvider.tsx, package-lock.json, package.json
- 관련 지라 티켓: [CM-89](https://starmix.atlassian.net/browse/CM-89)
- react-toastify 패키지 의존성을 추가
- Toast Provider를 정의하고 로그아웃 시에 적용
=> [CM-89] Toast 컴포넌트 생성 및 적용

app/projects/[id]/layout.tsx, app/projects/[id]/overview/page.tsx, app/projects/layout.tsx, app/projects/page.tsx, components/MainContent.tsx, components/project/ProjectNavbar.tsx, components/project/Sidebar.tsx, components/ui/sidebar.tsx
- 관련 지라 티켓: [CM-102](https://starmix.atlassian.net/browse/CM-102)
- 사이드바 토글의 위치를 내비게이션바로 변경
=> [CM-102] 사이드바 토글 위치 변경

app/privacy/page.tsx, app/terms/page.tsx
- 관련 지라 티켓: [CM-99](https://starmix.atlassian.net/browse/CM-99)
- 이용약관 및 개인정보 처리방침 페이지를 추가
=> [CM-99] 이용약관, 개인정보 처리방침 추가

app/globals.css, app/projects/[id]/overview/page.tsx, components/project/overview/SprintPeriodCard.tsx, components/ui/progress.tsx, public/tabler-run.svg
- 관련 지라 티켓: [CM-91](https://starmix.atlassian.net/browse/CM-91)
- 프로젝트 오버뷰 내 스프린트 위젯 디자인 적용
- 스프린트 재구성 링크를 연결
=> [CM-91] 프로젝트 오버뷰 스프린트 위젯 디자인 적용

app/projects/[id]/overview/page.tsx, app/projects/[id]/task/page.tsx, components/project/task/KanbanLogic.ts, components/project/task/KanbanView.tsx, components/project/task/TaskFilter.tsx, tailwind.config.js, types/userTask.ts
- 관련 지라 티켓: [CM-54](https://starmix.atlassian.net/browse/CM-54)
- 사용하지 않는 태스크 모달 창 슬라이드 애니메이션 코드 제거
- 스프린트 필터링 활성화
=> [CM-54] Task 페이지(칸반) sprint 필터링 기능 활성화

app/invite/[token]/page.tsx, app/layout.tsx, app/manifest.ts, app/privacy/page.tsx, app/terms/page.tsx, components/Navbar.tsx, components/project/home/ProjectList.tsx
- 관련 지라 티켓: [CM-120](https://starmix.atlassian.net/browse/CM-120)
- 프로젝트명 리브랜딩 적용
=> [CM-120] 프로젝트명 리브랜딩 적용

components/project/task/CalendarLogic.ts, components/project/task/CalendarView.tsx, components/project/task/KanbanView.tsx, components/project/task/TaskModal.tsx
- 관련 지라 티켓: [CM-125](https://starmix.atlassian.net/browse/CM-125)
- Task Modal에서 삭제 버튼 추가 및 기능 활성화
=> [CM-125] TaskModal에 삭제 버튼 및 DELETE API 연동

components/project/new/ChatPhase.tsx, components/project/new/FeatureTable.tsx, lib/api/projectCreation.ts, types/project-creation.ts
- 관련 지라 티켓: [CM-123](https://starmix.atlassian.net/browse/CM-123)
- 기능 명세 테이블 데이터의 변경이 피드백에 전달되도록 수정
=> [CM-123] 프로젝트 생성 기능 명세 Table 변경 사항을 피드백에 포함

app/projects/[id]/members/page.tsx, components/project/Sidebar.tsx, components/project/members/MemberTable.tsx, components/project/members/MembersList.tsx, components/project/members/dialogs/AddMemberDialog.tsx, components/project/members/dialogs/AddPMDialog.tsx, components/project/members/dialogs/EditMembersDialog.tsx, components/ui/label.tsx, hooks/useMemberSelection.ts, package-lock.json, package.json
- 관련 지라 티켓: [CM-92](https://starmix.atlassian.net/browse/CM-92)
- 팀원 정보 페이지를 추가
- 팀원 정보 수정 다이얼로그 UI 구현
- 팀원 또는 Product Manager 추가 다이얼로그 UI 구현
=> [CM-92] Members 페이지 생성

app/globals.css, app/projects/[id]/overview/page.tsx, app/projects/[id]/task/page.tsx, components/CheckMateSpinner.tsx, components/project/overview/MyTaskCard.tsx, components/project/overview/ScheduleCard.tsx, components/project/overview/daily-scrum/DailyScrumCard.tsx, components/project/task/KanbanView.tsx, components/project/task/TaskModal.tsx, types/project-definition.ts, types/table.ts
- 관련 지라 티켓: [CM-122](https://starmix.atlassian.net/browse/CM-122)
- 사용자에게 할당된 작업들을 불러오는 목록 생성
- 디자인 수정
- 목록 정렬 우선 순위 지정
=> [CM-122] Overview 내 작업 디자인 및 API 연동

app/globals.css, app/projects/[id]/overview/page.tsx, app/projects/[id]/task/page.tsx, components/project/overview/MyTaskCard.tsx, components/project/overview/ScheduleCard.tsx, components/project/overview/daily-scrum/DailyScrumCard.tsx, components/project/overview/daily-scrum/TaskItem.tsx, components/project/overview/daily-scrum/TaskList.tsx, components/project/task/TaskModal.tsx, components/ui/form.tsx, components/ui/label.tsx, hooks/useMemberSelection.ts, package-lock.json
- 관련 지라 티켓: [CM-121](https://starmix.atlassian.net/browse/CM-121)
- 이번 주(오늘의 날짜가 포함된 주) 7일 날짜 띄우기
- 오늘 날짜 표시
- 날짜에 따른 Task 목록 클라이언트 필터링
- Task 목록 순서 정렬 : 마감일 기준 오름차순
- 선택한 날짜 표시
- Task 목록이 비어있는 경우 안내 문구 띄우기
=> [CM-121] Overview 스케줄 디자인 및 API 연동

app/api/liveblocks-auth/route.ts, app/api/rooms/[roomId]/route.ts, app/projects/[id]/meeting-notes/[meetingId]/Editor.tsx, app/projects/[id]/meeting-notes/[meetingId]/MeetingNoteDetails.tsx, app/projects/[id]/meeting-notes/[meetingId]/Room.tsx, app/projects/[id]/meeting-notes/[meetingId]/Threads.tsx, app/projects/[id]/meeting-notes/[meetingId]/page.tsx, app/projects/[id]/meeting-notes/page.tsx, components/project/meeting-notes/MeetingNotesAdd.tsx, components/project/meeting-notes/MeetingNotesList.tsx, lib/api/meetingNotes.ts, package-lock.json, package.json, types/meeting.ts
- 관련 지라 티켓: [CM-93](https://starmix.atlassian.net/browse/CM-93)
- 회의록 목록 및 새 회의록 추가 API 연동
- Liveblocks API를 통한 회의록 사용자 인증 과정 추가
- Liveblocks API를 통한 회의록 작성일과 최종 편집일 정보 추가
- liveblocks/node 패키지 의존성 추가
=> [CM-93] Meeting Notes API 연동

app/globals.css, components/project/home/ProjectCard.tsx, components/project/members/MemberTable.tsx, components/project/members/dialogs/AddMemberDialog.tsx, components/project/members/dialogs/EditMembersDialog.tsx, components/project/new/ChatInput.tsx, components/project/new/ChatPhase.tsx, components/project/new/GenericEditableTable.tsx, components/project/new/ProjectWizard.tsx, components/project/new/TeamMemberTable.tsx, components/project/new/phases.ts, components/project/overview/SprintPeriodCard.tsx, components/ui/calendar.tsx, hooks/useProjectSSE.ts, package-lock.json, package.json, stores/useProjectStore.ts, types/NewProjectTeamMember.ts, types/project-definition.ts, types/project.ts, types/table.ts, types/userTask.ts
- 관련 지라 티켓: [CM-145](https://starmix.atlassian.net/browse/CM-145)
- Profile 타입에서 기술 스택 삭제
- 프로젝트 생성 시 개발 기간 캘린더 디자인 개선
- 프로젝트 생성 시 인원 구성에 리더를 기본으로 포함하도록 개선
- 프로젝트 생성 시 기능 명세 피드백의 로직 상 오류를 해결
- 프로젝트 카드에서 progress가 음수가 될 수 있는 문제를 해결
- 프로젝트 생성 시 채팅 메시지가 자동으로 스크롤되도록 개선
=> [CM-145] 프로젝트 생성 과정 QA 5건

components/project/new/ChatInput.tsx, components/project/new/ChatMessage.tsx, components/project/new/ChatPhase.tsx, components/project/new/FeatureTable.tsx, components/project/new/GenericEditableTable.tsx, components/project/new/ProjectWizard.tsx, components/project/new/phases.ts, components/ui/file-upload.tsx
- 관련 지라 티켓: [CM-156](https://starmix.atlassian.net/browse/CM-156)
- 프로젝트 생성 과정에서 사용자 입력 검증을 추가
- 프로젝트 생성 과정에서 빠른 답장을 추가
- 프로젝트 생성 과정에서 AI 응답 메시지 추가
=> [CM-156] 프로젝트 생성 시 UX 개선

components/project/sprint/DetailTaskTable.tsx, components/project/sprint/EditableTable.tsx, components/project/sprint/LoadingScreen.tsx, components/project/sprint/SprintReviewTable.tsx, components/project/sprint/SprintWizard.tsx, hooks/useProjectSSE.ts, hooks/useSprintSSE.ts, lib/api/sprintConfiguration.ts, types/sprint.ts
- 관련 지라 티켓: [CM-107](https://starmix.atlassian.net/browse/CM-107)
- 스프린트 구성 API 연동
- 스프린트 구성 시 세부 태스크 입력 로직 개선
=> [CM-107] 프로젝트 스프린트 재구성 API 연동

app/projects/[id]/settings/page.tsx, lib/api/projectSettings.ts, lib/constants.ts
- 관련 지라 티켓: [CM-140](https://starmix.atlassian.net/browse/CM-140)
- 설정 페이지 API 연동
=> [CM-140] Settings 페이지 API 연동

apps/web/app/projects/[id]/epic/page.tsx, apps/web/components/project/epic/DeleteEpicModal.tsx, apps/web/components/project/epic/NewEpicModal.tsx, apps/web/components/project/epic/task-list/task-list-header.tsx, apps/web/components/project/epic/task-list/task-list-table.tsx, apps/web/components/project/task/EpicSelectionModal.tsx
- 관련 지라 티켓: [CM-190](https://starmix.atlassian.net/browse/CM-190)
- 새 에픽 생성 버튼 UI 구현 및 API 연동
- 에픽 삭제 버튼 UI 구현 및 API 연동
=> [CM-190] Epic 생성 및 삭제 버튼 제작

.github/workflows/vercel.yml, apps/web/hooks/useMemberSelection.test.ts, jest.config.ts, package.json, packages/ui/src/hooks/useRandomColor.test.ts, pnpm-lock.yaml, tsconfig.json
- 관련 지라 티켓: [CM-180](https://starmix.atlassian.net/browse/CM-180)
- Unit 테스트용 패키지 의존성 추가
- Unit 테스트를 GitHub Actions 워크플로우에 포함
=> [CM-180] Unit 테스트 구성 개선

apps/web/app/projects/leaderboard/Podium.tsx, apps/web/app/projects/leaderboard/page.tsx, packages/api/src/statistics.ts
- 관련 지라 티켓: [CM-204](https://starmix.atlassian.net/browse/CM-204)
- 전체 리더보드 API 연동
- 팀 내부 워딩 규칙에 맞추어 용어 수정
=> [CM-204] 전체 리더보드 API 연동

apps/web/app/projects/[id]/(isActive)/epic/page.tsx, apps/web/components/project/epic/other/epicSprintFilter.tsx
- 관련 지라 티켓: [CM-203](https://starmix.atlassian.net/browse/CM-203)
- 스프린트 타이틀 옆 기간 표시
- 스프린트 필터링 코드 분리
- 오늘 날짜에 해당하는 스프린트 기간에 색상 차이를 줘서 표시
=> [CM-203] Epic 페이지의 Sprint 필터링 개선

apps/web/app/projects/[id]/(isActive)/settings/page.tsx, apps/web/components/project/new/ChatInput.tsx, apps/web/components/project/new/ChatPhase.tsx, apps/web/next.config.mjs, packages/api/src/objectStorage.ts, packages/ui/src/components/ui/file-upload.tsx
- 관련 지라 티켓: [CM-209](https://starmix.atlassian.net/browse/CM-209)
- 기능 정의 및 프로젝트 이미지 업로드 시 presigned URL 적용
=> [CM-209] presigned URL 적용(기능 정의 pdf 및 프로젝트 이미지)

apps/web/components/project/epic/NewEpicModal.tsx, apps/web/components/project/task/EpicSelectionModal.tsx, apps/web/components/project/task/KanbanLogic.ts, apps/web/components/project/task/KanbanTask.tsx, apps/web/components/project/task/KanbanView.tsx, apps/web/components/project/task/TaskComment.tsx, apps/web/components/project/task/TaskFilter.tsx, apps/web/components/project/task/TaskModal.tsx, packages/ui/src/components/ui/calendar.tsx
- 관련 지라 티켓: [CM-83](https://starmix.atlassian.net/browse/CM-83)
- 캘린더 디자인 변경 및 통일
- Task 페이지 필터를 위한 드롭다운 버그 해결
- 상세 Task 페이지 댓글 포커스
- Task 페이지 스크롤 활성화
- Task 페이지에서 바로 에픽 생성할 수 있도록 기능 구현
=> [CM-83] Task 페이지 최적화

apps/web/app/projects/[id]/(isActive)/billing/page.tsx, apps/web/app/projects/[id]/(isActive)/premium/page.tsx, apps/web/components/project/Sidebar.tsx, apps/web/package.json, packages/api/src/payment.ts, packages/types/src/project.ts, pnpm-lock.yaml
- 관련 지라 티켓: [CM-214](https://starmix.atlassian.net/browse/CM-214)
- 페이먼트 API 연동
- 프로젝트 결제 내역 API 연동
=> [CM-214] 페이먼트 API 연동

apps/web/app/projects/[id]/(isActive)/epic/page.tsx, apps/web/components/project/epic/epic-logic.ts, apps/web/components/project/epic/gantt/gantt.tsx, apps/web/components/project/epic/gantt/task-gantt-content.tsx, apps/web/components/project/epic/other/EpicProgress.ts, apps/web/components/project/epic/task-item/task-item.tsx, apps/web/components/project/epic/task-list/task-list-header.tsx, apps/web/components/project/epic/task-list/task-list-table.tsx, apps/web/hooks/useEpicColors.test.ts, apps/web/hooks/useEpicColors.ts, apps/web/hooks/useEpicProgress.test.ts, apps/web/hooks/useEpicProgress.ts, packages/types/src/epic.ts, packages/types/src/public-types.ts
- 관련 지라 티켓: [CM-219](https://starmix.atlassian.net/browse/CM-219)
- 에픽 진행률 계산 및 표시
- 에픽 진행률 표시로 인해 에픽 타이틀이 간트 차트에 안 뜨는 에러 해결
- 간트 차트 바 색상 버그 해결
=> [CM-219] 에픽 진행률 계산 및 표시

apps/web/app/projects/[id]/(isActive)/overview/page.tsx, apps/web/app/projects/[id]/(isActive)/settings/page.tsx, apps/web/components/project/members/MemberTable.tsx, apps/web/components/project/members/MembersList.tsx, apps/web/components/project/members/dialogs/AddMemberDialog.tsx, apps/web/components/project/members/dialogs/AddPMDialog.tsx, apps/web/components/project/members/dialogs/EditMembersDialog.tsx, apps/web/components/project/overview/ProjectHeader.tsx, apps/web/components/project/overview/SprintPeriodCard.tsx, apps/web/components/project/overview/daily-scrum/TaskItem.tsx, apps/web/components/project/overview/daily-scrum/TaskList.tsx, apps/web/lib/task-select-styles.ts, packages/api/src/member.ts, packages/api/src/projectSettings.ts, packages/ui/package.json, packages/ui/src/lib/select-styles.ts, packages/ui/src/lib/task-select-styles.ts, pnpm-lock.yaml
- 관련 지라 티켓: [CM-215](https://starmix.atlassian.net/browse/CM-215)
- Product Manager인 멤버의 체크박스가 선택되지 않던 문제를 해결
- Product Manager가 존재하지 않을 때 Members가 보이지 않는 문제를 해결
- 프로젝트 리더의 정보가 수정이 안되는 문제를 해결
=> [CM-215] Members 페이지에서 PM인 멤버의 체크박스가 선택되지 않는 이슈

apps/web/app/projects/[id]/(isActive)/task/page.tsx, apps/web/components/project/epic/other/epicSprintFilter.tsx, apps/web/components/project/task/KanbanColumn.tsx, apps/web/components/project/task/KanbanView.tsx, apps/web/components/project/task/TaskFilter.tsx
- 관련 지라 티켓: [CM-218](https://starmix.atlassian.net/browse/CM-218)
- 스프린트 필터링 드롭다운 목록 순서 설정
- 멤버 필터링 버그 개선
- Task add시 툴팁 추가
=> [CM-218] Task 페이지 버그 개선

apps/web/components/project/new/ChatInput.tsx, apps/web/components/project/new/ChatMessage.tsx, apps/web/components/project/new/ChatPhase.tsx, apps/web/components/project/new/CompletionPhase.tsx, apps/web/components/project/new/TeamMemberTable.tsx
- 관련 지라 티켓: [CM-223](https://starmix.atlassian.net/browse/CM-223)
- 프로젝트 생성 기능 정의 시 체크한 기능에 대한 빠른 답변을 추가
- 프로젝트 생성 시 사용자 입력 검증을 강화
=> [CM-223] 프로젝트 기능 정의 시 input 위 버튼 추가

apps/web/components/project/Sidebar.tsx, apps/web/providers/AuthProvider.tsx
- 관련 지라 티켓: [CM-141](https://starmix.atlassian.net/browse/CM-141)
- 사이드바 로그아웃 API 연동
- 사이드바 배너 텍스트 개선
=> [CM-141] 사이드바 개선 관련 QA

apps/web/app/projects/leaderboard/page.tsx
- 관련 지라 티켓: [CM-231](https://starmix.atlassian.net/browse/CM-231)
- 리더보드 표시 방식 개선
=> [CM-231] 리더보드 개선 관련 QA
